import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
// import Document, { Html, Head, Main, NextScript } from 'next/document';
<link
  href="https://fonts.googleapis.com/css2?family=Roboto+Mono&family=Inter&display=swap"
  rel="stylesheet"
/>

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({ // Renamed variable correctly
  variable: "--font-roboto-mono", // Fixed CSS variable name
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
